# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory
WORKDIR /dist

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Run Prisma Migrations
RUN npx prisma migrate deploy

# Expose the port the app runs on
EXPOSE 8000

# Start the application
CMD ["npm", "dev"]